#!/bin/bash

CODEGEN=../bin/c_codegen
EMULATOR=qemu-mips
MIPS_GCC=mips-linux-gnu-gcc
MAIN=main_fncall.c
MEDIATOR=fncall.c
OUTDIR=build_fncall

if [ $# -eq 0 ]; then
  for i in input/*.c; do
    FILENAME=$(basename $i .c);

    echo "FILE: " $FILENAME
    ###################################
    ## Compile everything using gcc to get a reference (native) version

    ${MIPS_GCC} -static ${MAIN} $i ${MEDIATOR} -o ${OUTDIR}/${FILENAME}.gccref
    ${EMULATOR} ${OUTDIR}/${FILENAME}.gccref > output/${FILENAME}.reference

    ###################################
    ## Compile the function using your compiler and link it with the main using gcc

    # TODO: C pre-processor?

    # Compile the main and the assembly generated by your compiler
    ${MIPS_GCC} -static ${MAIN} ${OUTDIR}/${FILENAME}.s -o ${OUTDIR}/${FILENAME}
  
    # Run the executable
    ${EMULATOR} ${OUTDIR}/${FILENAME} > output/${FILENAME}.got

    ##################################
    ## Compare the outputs
    diff output/${FILENAME}.got output/${FILENAME}.reference > output/${FILENAME}.diff;
    if [[ $? != 0 ]]; then
      echo "${FILENAME}, FAIL, see output/${FILENAME}.diff";
    else
      echo "${FILENAME}, pass";
    fi
  done
else
  FILENAME=$1

    ###################################
    ## Compile everything using gcc to get a reference (native) version
    ${MIPS_GCC} -static ${MAIN} input/${FILENAME}.c ${MEDIATOR} -o ${OUTDIR}/${FILENAME}.gccref
    ${EMULATOR} ${OUTDIR}/${FILENAME}.gccref > output/${FILENAME}.reference

    ###################################
    ## Compile the function using your compiler and link it with the main using gcc

    # TODO: C pre-processor?

    # Compile the main and the assembly generated by your compiler
    ${MIPS_GCC} -static ${MAIN} ${OUTDIR}/${FILENAME}.s -o ${OUTDIR}/${FILENAME}
  
    # Run the executable
    ${EMULATOR} ${OUTDIR}/${FILENAME} > output/${FILENAME}.got

    ##################################
    ## Compare the outputs
    diff output/${FILENAME}.got output/${FILENAME}.reference > output/${FILENAME}.diff;
    if [[ $? != 0 ]]; then
      echo "${FILENAME}, FAIL, see output/${FILENAME}.diff";
    else
      echo "${FILENAME}, pass";
    fi
fi


