#line 2 "src/c_lexer.yy.cpp"

#line 4 "src/c_lexer.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[277] =
    {   0,
        0,    0,   93,   91,    2,    1,   83,   91,   74,   85,
       78,   91,   43,   44,   79,   80,   72,   81,   48,   84,
       38,   37,   61,   75,   86,   76,   87,   60,   35,   35,
       41,   42,   88,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   45,   77,
       46,   82,   74,   57,    0,   89,    0,   73,   64,   58,
       69,    0,    0,   62,   50,   65,   51,   66,   49,    0,
       36,   63,   36,   38,    0,    0,   38,   38,    0,   37,
       37,   37,   52,   54,   56,   55,   53,   35,   35,    0,
        0,   70,   35,   35,   35,   35,   35,   35,   30,   35,

       35,   35,   35,   35,   35,   31,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   71,   59,    0,
        0,    0,    0,   40,    0,    0,    0,   47,    0,   36,
        0,   36,   38,   38,   39,   37,   37,   67,   68,    0,
        0,    0,    0,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   24,   35,    5,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,    0,    0,    0,    0,    0,    0,   36,   36,
       39,   39,    0,    0,    0,    0,    0,    0,    3,   35,
       11,   15,   35,   35,   35,   35,    8,   12,   35,   35,

       28,    9,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   26,   35,   35,   90,    0,    0,    0,
        0,   39,   39,    0,    0,    0,    0,    7,   19,   35,
       35,   35,   35,   20,   35,   35,   21,   35,   35,   35,
       35,   35,   35,   18,   35,   35,   33,    0,    0,    0,
        0,   35,   35,    4,   16,   35,   17,   25,   34,   32,
        6,   10,   35,   35,   35,   35,   27,   35,   14,   35,
       35,   23,   13,   22,   29,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   31,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        5,    5,    5,    5,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[289] =
    {   0,
        0,  301,  297, 1103, 1103, 1103,  263,   61,  277,  251,
       59,  237, 1103, 1103,  228,   55, 1103,   56,   54,  227,
       81,  125, 1103, 1103,   52,  203,   53, 1103,   66,   84,
     1103, 1103,  199,   72,   97,   87,  100,  115,  128,  140,
      150,  164,  167,  176,  170,  179,  184,  187, 1103,   45,
     1103, 1103,   92, 1103,   89, 1103,  231, 1103, 1103, 1103,
     1103,  101,  286, 1103, 1103, 1103, 1103, 1103, 1103,  198,
      225, 1103,  280,   93,  200,  245,   55,   91,    0,    0,
       98,  118,  189, 1103, 1103, 1103,  156,    0,  192,  126,
      142, 1103,  206,  259,  228,  295,  298,  219,  274,  331,

      334,  337,  340,  343,  346,  349,  352,  355,  358,  361,
      364,  368,  380,  375,  391,  396,  400, 1103, 1103,    0,
      157,  284,    0, 1103,  166,  413,    0, 1103,  415, 1103,
      420,  431, 1103, 1103,  421, 1103, 1103, 1103, 1103,  173,
      475,  224,  530,  436,  445,  439,  452,  448,  470,  477,
      480,  501,  518,  523,  526,  533,  539,  544,  552,  556,
      572,  559,  575,  581,  584,  587,  595,  600,  603,  609,
      614,  625,  169,  636,  669,  629,  704,  638,  647, 1103,
      185,  124,  250,  664,    0,  262,  644,    0,  641,  673,
      666,  682,  696,  707,  699,  710,  716,  730,  741,  744,

      747,  750,  753,  756,  759,  762,  765,  769,  772,  777,
      782,  800,  807,  810,  813,  816, 1103,  271,    0,  311,
        0, 1103, 1103,  803,  864,  828,  899,  821,  824,  835,
      841,  846,  859,  852,  855,  893,  876,  903,  911,  896,
      927,  930,  937,  933,  940,  943,  946,  275,    0,  388,
        0,  949,  952,  958,  965,  968,  973,  976,  979,  982,
      993,  996,  999, 1002, 1005, 1008, 1011, 1014, 1017, 1020,
     1027, 1036, 1039, 1044, 1052, 1103, 1073, 1078, 1080,  161,
     1082, 1087, 1092, 1097,  124,  118,   85,   79
    } ;

static yyconst flex_int16_t yy_def[289] =
    {   0,
      276,    1,  276,  276,  276,  276,  276,  277,  276,  276,
      276,  278,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  279,  279,
      276,  276,  276,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  276,  276,
      276,  276,  276,  276,  277,  276,  276,  276,  276,  276,
      276,  278,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,   21,  276,  276,  276,  276,  280,   22,
      276,  276,  276,  276,  276,  276,  276,  281,  279,  282,
      283,  276,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  276,  276,  284,
      277,  277,  285,  276,  278,  278,  286,  276,  276,  276,
      276,  276,  276,  276,  280,  276,  276,  276,  276,  282,
      276,  283,  276,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  284,  277,  277,  278,  278,  276,  276,  276,
      276,  276,  282,  282,  287,  283,  283,  288,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  276,  277,  175,  278,
      177,  276,  276,  282,  282,  283,  283,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  282,  225,  283,
      227,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,    0,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276
    } ;

static yyconst flex_uint16_t yy_nxt[1170] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   29,   29,   31,    4,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   29,   41,   29,   42,   29,
       29,   29,   29,   43,   44,   45,   46,   47,   48,   29,
       29,   29,   49,   50,   51,   52,   56,   60,   65,  118,
       70,   67,   71,   71,   71,   83,   84,   86,   87,   66,
       68,   69,  227,   61,   88,   88,   88,  133,  225,   90,
       88,   88,   88,   91,   56,  120,   57,   73,   58,   74,

       74,   75,   88,   88,   88,   88,   88,   88,  119,   76,
      124,  133,   77,   78,   79,   88,   88,   88,   88,   88,
       88,  177,  134,   76,   57,   95,  276,  175,   93,   77,
      136,   56,   96,   88,   88,   88,   63,   78,   97,  134,
       79,   73,   98,   80,   80,   80,   88,   88,   88,  137,
       94,   99,  276,   76,  136,  223,   81,   82,   88,   88,
       88,  141,   56,  100,  135,  101,  137,   76,   88,   88,
       88,  217,  223,   81,  102,  124,  103,  143,   56,  104,
      139,   82,   88,   88,   88,   88,   88,   88,   88,   88,
       88,  105,   57,  106,   88,   88,   88,   88,   88,   88,

      107,   63,   88,   88,   88,   88,   88,   88,  141,  109,
       88,   88,   88,  138,  128,  108,   73,  222,   75,   75,
       75,  110,  111,   92,   88,   88,   88,   85,   76,  115,
      114,  112,  117,  124,  113,  116,  121,   88,   88,   88,
      121,  222,   76,   71,   71,   71,   88,   88,   88,  122,
      122,   72,   64,  129,  130,   56,  130,  121,  131,  143,
      131,  144,  149,  132,  132,  132,  121,  129,  130,  121,
      121,  124,   63,  130,  121,   59,   56,   88,   88,   88,
       56,  121,  146,   58,  121,  141,  121,   54,  121,   56,
      123,  125,   88,   88,   88,  125,  276,  143,   71,   71,

       71,  145,  174,  174,  126,  126,   57,   53,  129,  130,
      141,  130,  125,   88,   88,   88,   88,   88,   88,   57,
      124,  125,  129,  130,  125,  125,  276,  276,  130,  125,
      150,  276,  276,  147,  276,  276,  125,  276,  276,  125,
      276,  125,  276,  125,  276,  127,   63,  276,  148,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,  151,   88,   88,   88,  276,
      152,  154,  153,   88,   88,   88,  155,  124,   88,   88,

       88,  156,  159,  276,  276,  158,  164,  157,  162,   88,
       88,   88,  161,  160,   88,   88,   88,  276,   88,   88,
       88,  165,  124,  143,  276,  163,  166,  167,  178,  276,
      178,  176,  176,  179,  179,  179,  276,  168,  132,  132,
      132,  276,  170,  276,  171,  169,  172,  276,   63,  132,
      132,  132,  181,  182,   88,   88,   88,   88,   88,   88,
      180,  276,  180,   88,   88,   88,   88,   88,   88,  181,
       88,   88,   88,  276,  180,  276,  276,  182,  276,  180,
      183,  191,  276,  190,  183,  276,  276,  189,   88,   88,
       88,  276,  276,  184,  184,   88,   88,   88,   88,   88,

       88,  183,  193,  194,  276,  192,  276,  276,  195,  276,
      183,  276,  276,  183,  183,  276,  196,  276,  183,   88,
       88,   88,  197,  276,  276,  183,  276,  276,  183,  276,
      183,  276,  183,  276,  185,  186,   88,   88,   88,  186,
      276,   88,   88,   88,   88,   88,   88,  276,  187,  187,
      198,   88,   88,   88,  276,  276,  186,   88,   88,   88,
      199,  200,   88,   88,   88,  186,  276,  276,  186,  186,
       88,   88,   88,  186,   88,   88,   88,   88,   88,   88,
      186,  276,  276,  186,  201,  186,  276,  186,  202,  188,
       88,   88,   88,   88,   88,   88,  276,  276,  203,   88,

       88,   88,   88,   88,   88,   88,   88,   88,  276,  206,
      276,  276,  204,   88,   88,   88,  276,  207,   88,   88,
       88,   88,   88,   88,  276,  205,  276,   88,   88,   88,
      276,  276,   88,   88,   88,  276,  208,  211,  124,  276,
      209,   56,  210,   88,   88,   88,  276,  220,  220,  213,
      214,  212,  215,  124,  218,  218,  179,  179,  179,   88,
       88,   88,  226,  226,   63,  179,  179,  179,  276,   56,
      276,   57,  276,  216,   56,  276,  130,  276,  130,  143,
      276,  276,  224,  224,   88,   88,   88,  219,  219,  219,
      130,   88,   88,   88,  276,  130,  219,  219,  219,  141,

       88,   88,   88,  276,   57,  276,  276,  219,  219,  219,
      219,  219,  219,  124,   88,   88,   88,   88,   88,   88,
      228,  276,  221,  221,  221,   88,   88,   88,   88,   88,
       88,  221,  221,  221,   88,   88,   88,  276,  276,   63,
      276,  276,  221,  221,  221,  221,  221,  221,   88,   88,
       88,  229,  276,  230,  276,  231,  276,  276,  232,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,  276,   88,   88,   88,
       88,   88,   88,  276,  233,   88,   88,   88,  276,  234,

       88,   88,   88,  276,  238,  276,  276,  235,   56,  236,
      276,  276,  241,  276,  237,  240,  239,  242,   88,   88,
       88,  248,  248,  243,  276,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,  124,  141,   88,
       88,   88,   88,   88,   88,  276,  250,  250,  276,  276,
      244,  245,  276,   88,   88,   88,  276,  276,  247,   88,
       88,   88,  276,  143,   88,   88,   88,  276,  246,   56,
       88,   88,   88,   88,   88,   88,  276,   88,   88,   88,
      276,  276,  249,  249,  249,  252,  276,  276,  254,  253,
      276,  249,  249,  249,   88,   88,   88,  276,  276,  141,

      276,  276,  249,  249,  249,  249,  249,  249,  124,  255,
      256,   88,   88,   88,   88,   88,   88,  251,  251,  251,
      276,   88,   88,   88,  276,  276,  251,  251,  251,   88,
       88,   88,  276,  276,  143,  276,  260,  251,  251,  251,
      251,  251,  251,  257,  258,   88,   88,   88,   88,   88,
       88,   88,   88,   88,  259,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,  276,  276,  262,   88,   88,   88,  263,
      276,  276,  261,   88,   88,   88,   88,   88,   88,  265,
      264,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,  276,  276,  266,  276,  267,  276,  276,
      268,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,  276,  269,  276,  270,   88,   88,   88,  276,  276,
      272,  276,  276,  271,   88,   88,   88,   88,   88,   88,
      276,  274,   88,   88,   88,  276,  276,  273,  276,  275,
       88,   88,   88,   55,  276,   55,   55,   55,   62,  276,
      276,   62,   62,   89,   89,   88,   88,  140,  276,  140,
      140,  140,  142,  276,  276,  142,  142,  173,  276,  173,

      173,  173,    3,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276
    } ;

static yyconst flex_int16_t yy_chk[1170] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   11,   16,   50,
       19,   18,   19,   19,   19,   25,   25,   27,   27,   16,
       18,   18,  288,   11,   29,   29,   29,   77,  287,   30,
       34,   34,   34,   30,   55,   53,    8,   21,   53,   21,

       21,   21,   30,   30,   30,   36,   36,   36,   50,   21,
       62,   77,   21,   21,   21,   35,   35,   35,   37,   37,
       37,  286,   78,   21,   55,   36,   74,  285,   34,   21,
       81,   90,   36,   38,   38,   38,   62,   21,   36,   78,
       21,   22,   37,   22,   22,   22,   39,   39,   39,   82,
       35,   37,   74,   22,   81,  182,   22,   22,   40,   40,
       40,   90,  121,   38,  280,   38,   82,   22,   41,   41,
       41,  173,  182,   22,   38,  125,   39,   91,  140,   39,
       87,   22,   42,   42,   42,   43,   43,   43,   45,   45,
       45,   40,  121,   41,   44,   44,   44,   46,   46,   46,

       41,  125,   47,   47,   47,   48,   48,   48,  140,   43,
       89,   89,   89,   83,   70,   42,   75,  181,   75,   75,
       75,   44,   44,   33,   93,   93,   93,   26,   75,   46,
       45,   44,   48,  142,   44,   47,   57,   98,   98,   98,
       57,  181,   75,   71,   71,   71,   95,   95,   95,   57,
       57,   20,   15,   71,   71,  183,   71,   57,   76,  142,
       76,   93,   98,   76,   76,   76,   57,   71,   71,   57,
       57,  186,   12,   71,   57,   10,  218,   94,   94,   94,
      248,   57,   95,    9,   57,  183,   57,    7,   57,  122,
       57,   63,   99,   99,   99,   63,    3,  186,   73,   73,

       73,   94,  122,  122,   63,   63,  218,    2,   73,   73,
      248,   73,   63,   96,   96,   96,   97,   97,   97,  122,
      220,   63,   73,   73,   63,   63,    0,    0,   73,   63,
       99,    0,    0,   96,    0,    0,   63,    0,    0,   63,
        0,   63,    0,   63,    0,   63,  220,    0,   97,  100,
      100,  100,  101,  101,  101,  102,  102,  102,  103,  103,
      103,  104,  104,  104,  105,  105,  105,  106,  106,  106,
      107,  107,  107,  108,  108,  108,  109,  109,  109,  110,
      110,  110,  111,  111,  111,  100,  112,  112,  112,    0,
      101,  103,  102,  114,  114,  114,  104,  250,  113,  113,

      113,  105,  109,    0,    0,  108,  112,  107,  111,  115,
      115,  115,  110,  109,  116,  116,  116,    0,  117,  117,
      117,  112,  126,  250,    0,  111,  113,  114,  129,    0,
      129,  126,  126,  129,  129,  129,    0,  115,  131,  131,
      131,    0,  116,    0,  116,  115,  117,    0,  126,  132,
      132,  132,  135,  135,  144,  144,  144,  146,  146,  146,
      132,    0,  132,  145,  145,  145,  148,  148,  148,  135,
      147,  147,  147,    0,  132,    0,    0,  135,    0,  132,
      141,  146,    0,  145,  141,    0,    0,  144,  149,  149,
      149,    0,    0,  141,  141,  150,  150,  150,  151,  151,

      151,  141,  148,  148,    0,  147,    0,    0,  149,    0,
      141,    0,    0,  141,  141,    0,  150,    0,  141,  152,
      152,  152,  151,    0,    0,  141,    0,    0,  141,    0,
      141,    0,  141,    0,  141,  143,  153,  153,  153,  143,
        0,  154,  154,  154,  155,  155,  155,    0,  143,  143,
      152,  156,  156,  156,    0,    0,  143,  157,  157,  157,
      153,  154,  158,  158,  158,  143,    0,    0,  143,  143,
      159,  159,  159,  143,  160,  160,  160,  162,  162,  162,
      143,    0,    0,  143,  156,  143,    0,  143,  158,  143,
      161,  161,  161,  163,  163,  163,    0,    0,  159,  164,

      164,  164,  165,  165,  165,  166,  166,  166,    0,  162,
        0,    0,  160,  167,  167,  167,    0,  163,  168,  168,
      168,  169,  169,  169,    0,  161,    0,  170,  170,  170,
        0,    0,  171,  171,  171,    0,  164,  167,  176,    0,
      165,  174,  166,  172,  172,  172,    0,  176,  176,  169,
      170,  168,  171,  187,  174,  174,  178,  178,  178,  189,
      189,  189,  187,  187,  176,  179,  179,  179,    0,  184,
        0,  174,    0,  172,  175,    0,  179,    0,  179,  187,
        0,    0,  184,  184,  191,  191,  191,  175,  175,  175,
      179,  190,  190,  190,    0,  179,  175,  175,  175,  184,

      192,  192,  192,    0,  175,    0,    0,  175,  175,  175,
      175,  175,  175,  177,  193,  193,  193,  195,  195,  195,
      190,    0,  177,  177,  177,  194,  194,  194,  196,  196,
      196,  177,  177,  177,  197,  197,  197,    0,    0,  177,
        0,    0,  177,  177,  177,  177,  177,  177,  198,  198,
      198,  193,    0,  194,    0,  195,    0,    0,  196,  199,
      199,  199,  200,  200,  200,  201,  201,  201,  202,  202,
      202,  203,  203,  203,  204,  204,  204,  205,  205,  205,
      206,  206,  206,  207,  207,  207,    0,  208,  208,  208,
      209,  209,  209,    0,  199,  210,  210,  210,    0,  200,

      211,  211,  211,    0,  206,    0,    0,  203,  224,  204,
        0,    0,  209,    0,  205,  208,  207,  210,  212,  212,
      212,  224,  224,  211,    0,  213,  213,  213,  214,  214,
      214,  215,  215,  215,  216,  216,  216,  226,  224,  228,
      228,  228,  229,  229,  229,    0,  226,  226,    0,    0,
      212,  213,    0,  230,  230,  230,    0,    0,  216,  231,
      231,  231,    0,  226,  232,  232,  232,    0,  215,  225,
      234,  234,  234,  235,  235,  235,    0,  233,  233,  233,
        0,    0,  225,  225,  225,  230,    0,    0,  232,  231,
        0,  225,  225,  225,  237,  237,  237,    0,    0,  225,

        0,    0,  225,  225,  225,  225,  225,  225,  227,  233,
      235,  236,  236,  236,  240,  240,  240,  227,  227,  227,
        0,  238,  238,  238,    0,    0,  227,  227,  227,  239,
      239,  239,    0,    0,  227,    0,  240,  227,  227,  227,
      227,  227,  227,  236,  238,  241,  241,  241,  242,  242,
      242,  244,  244,  244,  239,  243,  243,  243,  245,  245,
      245,  246,  246,  246,  247,  247,  247,  252,  252,  252,
      253,  253,  253,    0,    0,  242,  254,  254,  254,  243,
        0,    0,  241,  255,  255,  255,  256,  256,  256,  246,
      245,  257,  257,  257,  258,  258,  258,  259,  259,  259,

      260,  260,  260,    0,    0,  252,    0,  253,    0,    0,
      256,  261,  261,  261,  262,  262,  262,  263,  263,  263,
      264,  264,  264,  265,  265,  265,  266,  266,  266,  267,
      267,  267,  268,  268,  268,  269,  269,  269,  270,  270,
      270,    0,  263,    0,  264,  271,  271,  271,    0,    0,
      266,    0,    0,  265,  272,  272,  272,  273,  273,  273,
        0,  270,  274,  274,  274,    0,    0,  268,    0,  271,
      275,  275,  275,  277,    0,  277,  277,  277,  278,    0,
        0,  278,  278,  279,  279,  281,  281,  282,    0,  282,
      282,  282,  283,    0,    0,  283,  283,  284,    0,  284,

      284,  284,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/c_lexer.lex"
/* 
	Flex will pick the longest matching token
	For matches of the same length it will pick the first 
	Flex cares about white space. Start all rules at the very beginning of a line
*/
/* include this option to avoid dependencies on function yywrap (yywrap is only needed if more than one file need to be processed) */
#line 16 "src/c_lexer.lex"
#include <iostream>
#include <string>
#include <sstream>
#include <cstdlib>
#include "c_parser.tab.hpp"

using namespace std;


/* ============================================== Named patterns definitions ============================================== */
/* 
	1. be EXTREMELY careful with operators that are also defined in regexes: +  *  |  ^  [  ]  (  )  {  }  .  ?
	2. EXTREMELY careful with order - don't let a single symbol operator to be recognized inappropriately as part of a bigger operator
*/
/* -------------------------------------------------------- KEYWORDS -------------------------------------------------------- */
/* -------------------------------------------------------- IDENTIFIERS -------------------------------------------------------- */
/* Pointers are in the operators scope */
/* -------------------------------------------------------- CONSTANTS -------------------------------------------------------- */
/* 0.0 is recognized */
/*Integer_const			(({DECIMAL_CONST}{INT_SUFFIX}?)|({HEX_CONST}{INT_SUFFIX}?)|({OCTAL_CONST}{INT_SUFFIX}?))*/
/* NOTE: 0 currently recognized in OCTAL */
/*
SIMPLE_ESC_SEQUENCE		(\'|\"|\\?|\\|\a|\b|\f|\\n|\\r|\\t|\v)					
SIMPLE_ESC_SEQUENCE		(((\\)(\?))|((\\){2})|(\a)|(\b)|(\f)|(\n)|(\r)|(\t)|(\v))
*/
/* -------------------------------------------------------- STRING LITERALS ------------------------------------------------------- */
/* -------------------------------------------------------- OPERATORS -------------------------------------------------------- */
/* -------------------------------------------------------- INVALID -------------------------------------------------------- */
/* -------------------------------------------------------- PREPROCESSOR -------------------------------------------------------- */
/* NB: Regexes that might need fixing:
	SIMPLE_ESC_SEQUENCE
	SCHAR 	- should be fine
*/
/* ============================================== Pattern matching rule section ============================================== */
#line 859 "src/c_lexer.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 114 "src/c_lexer.lex"

#line 1082 "src/c_lexer.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 277 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1103 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 115 "src/c_lexer.lex"
{ input_file_line++; source_line++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 116 "src/c_lexer.lex"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 117 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return AUTO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return DOUBLE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return INT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 120 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return STRUCT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 121 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return BREAK; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 122 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return ELSE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LONG; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 124 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return SWITCH; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 125 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return CASE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 126 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return ENUM; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 127 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return REGISTER; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 128 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return TYPEDEF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 129 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return CHAR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return EXTERN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 131 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return RETURN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 132 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return UNION; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 133 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return CONST; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 134 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return FLOAT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 135 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return SHORT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 136 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return UNSIGNED; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 137 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return CONTINUE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 138 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return FOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 139 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return SIGNED; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 140 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return VOID; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 141 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return DEFAULT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 142 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return GOTO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 143 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return VOLATILE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 144 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return DO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 145 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return IF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 146 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return STATIC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 147 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return WHILE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 148 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return SIZEOF; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 149 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 150 "src/c_lexer.lex"
{ yylval.floatval = to_double64(yytext); return FLOATING_CONST; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 151 "src/c_lexer.lex"
{ yylval.uint64val = dec_to_uint64(yytext); return INTEGER_CONST; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 152 "src/c_lexer.lex"
{ yylval.uint64val = dec_to_uint64(yytext); return INTEGER_CONST; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 153 "src/c_lexer.lex"
{ yylval.uint64val = dec_to_uint64(yytext); return INTEGER_CONST; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "src/c_lexer.lex"
{ return CHAR_CONST; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "src/c_lexer.lex"
{ return LSQUARE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 156 "src/c_lexer.lex"
{ return RSQUARE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 157 "src/c_lexer.lex"
{ return LBRACKET; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 158 "src/c_lexer.lex"
{ return RBRACKET; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 159 "src/c_lexer.lex"
{ return LCURLY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 160 "src/c_lexer.lex"
{ return RCURLY; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 161 "src/c_lexer.lex"
{ return THREE_DOTS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 162 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return DOT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 163 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return PTR_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 164 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return PLUS_PLUS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 165 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return MINUS_MINUS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 166 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LSHIFT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 167 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return RSHIFT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 168 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LESS_OR_EQUAL; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 169 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return MORE_OR_EQUAL; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 170 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LOGICAL_EQUALITY; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 171 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LOGICAL_INEQUALITY; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 172 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LOGICAL_AND; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 173 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LOGICAL_OR; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 174 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return Q_MARK; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 175 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return COLON; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 176 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return MULT_EQUALS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 177 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return DIV_EQUALS; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 178 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return PERCENT_EQUALS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 179 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return PLUS_EQUALS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 180 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return MINUS_EQUALS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 181 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LSHIFT_EQUALS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 182 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return RSHIFT_EQUALS; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 183 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return AND_EQUALS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 184 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return XOR_EQUALS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 185 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return OR_EQUALS; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 186 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return COMMA; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 187 "src/c_lexer.lex"
{ return HASH; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 188 "src/c_lexer.lex"
{ return HASH_HASH; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 189 "src/c_lexer.lex"
{ return SEMI_COLON; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 190 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return EQUALS; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 191 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return BITWISE_OR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 192 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return BITWISE_AND; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 193 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return MULT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 194 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return PLUS; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 195 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return MINUS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 196 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return WAVE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 197 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return EXL_MARK; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 198 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return DIV; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 199 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return PERCENT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 200 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LOGICAL_LESS; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 201 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return LOGICAL_MORE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 202 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return BITWISE_XOR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 203 "src/c_lexer.lex"
{ yylval.strval = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 90:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 204 "src/c_lexer.lex"
{ process_prep_include(yytext); yylval.strval = strdup(yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 205 "src/c_lexer.lex"
{ cerr<<"In file "<<source_file<<": Invalid syntax at line "<<source_line<<endl; exit(EXIT_FAILURE); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 206 "src/c_lexer.lex"
ECHO;
	YY_BREAK
#line 1604 "src/c_lexer.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 277 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 277 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 276);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 206 "src/c_lexer.lex"


/* ==================== User function section - optional. Define the functions called on regex matches here ==================== */

//{Integer_const}		{ yylval.uint64val = atoi(yytext); return INTEGER_CONST; }


/*
int main(){
  	cerr<<"Lexing starts"<<endl;

	yylex();

  	cerr<<"Lexing starts"<<endl;

	return 0;
}
*/
